class DataModule{
	'block'=[
			{
				'blockstock':[
					{
						"blockcode":"2006",
						"secuabbr":"鞍钢股份",
						"secucode":"000898",
						"closeprice":31800,
						"changeratio":495,
						"changeratio5":160,
						"ztcountdesc":"",
						"exashareratio":2.61,
						"netbuysum":7205235.45,
						"isindustry":1,
						"ishot":0,
						"label":"",
						"reason":"东北龙头钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校",
					},
					{
						"blockcode":"2006",
						"secuabbr":"宝钢股份",
						"secucode":"600019",
						"closeprice":61500,
						"changeratio":389,
						"changeratio5":-81,
						"ztcountdesc":"",
						"exashareratio":6.05,
						"netbuysum":33056903.92,
						"isindustry":1,
						"ishot":0,
						"label":"",
						"reason":"钢铁龙头钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校",
					},
					{
						"blockcode":"2006",
						"secuabbr":"河钢股份",
						"secucode":"000709",
						"closeprice":22700,
						"changeratio":271,
						"changeratio5":0,
						"ztcountdesc":"",
						"exashareratio":1.90,
						"netbuysum":2597912.87,
						"isindustry":1,
						"ishot":0,
						"label":"",
						"reason":"河北龙头钢企钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校"
					},
					{
						"blockcode":"2006",
						"secuabbr":"包钢股份",
						"secucode":"600010",
						"closeprice":11800,
						"changeratio":85,
						"changeratio5":-167,
						"ztcountdesc":"",
						"exashareratio":1.92,
						"netbuysum":4616195.93,
						"isindustry":1,
						"ishot":0,
						"label":"",
						"reason":"稀土钢龙头钢企拿回家阿军校",
					},
					{
						"blockcode":"2006",
						"secuabbr":"中信特钢",
						"secucode":"000708",
						"closeprice":202400,
						"changeratio":55,
						"changeratio5":-316,
						"ztcountdesc":"",
						"exashareratio":3.37,
						"netbuysum":18219113.78,
						"isindustry":1,
						"ishot":0,
						"label":"",
						"reason":"特钢龙头钢企拿回家阿军校钢企拿回家阿军校钢企拿回家阿军校",
					}
				]
			}
		]
}
export default new DataModule()